## TensorFlow 2 quickstart for beginners with GPU
### July 19, 2020
### Chan-Hee Park 

In [14]:
import tensorflow as tf

In [15]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

predictions = model(x_train[:1]).numpy()
predictions

array([[-0.0773599 , -0.0611302 ,  0.43447894, -0.5259727 , -0.1760886 ,
        -0.3410074 ,  0.19884717,  0.13311262, -0.12706788, -0.04822886]],
      dtype=float32)

In [16]:
tf.nn.softmax(predictions).numpy()

array([[0.09495852, 0.09651225, 0.15842465, 0.06063228, 0.08603133,
        0.07295134, 0.1251668 , 0.11720362, 0.09035373, 0.09776545]],
      dtype=float32)

In [17]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [18]:
loss_fn(y_train[:1], predictions).numpy()

2.6179626

In [19]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [20]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2956 - accuracy: 0.9138
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1443 - accuracy: 0.9565
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1058 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0882 - accuracy: 0.9723
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0741 - accuracy: 0.9766


In [21]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0737 - accuracy: 0.9778


[0.07368842512369156, 0.9778000116348267]

In [22]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [23]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.82809668e-08, 1.22490178e-08, 2.45290971e-06, 1.88540434e-05,
        1.25387357e-11, 5.79040993e-09, 3.74711633e-12, 9.99978185e-01,
        1.78503257e-07, 3.54422042e-07],
       [3.27197718e-08, 4.73083564e-05, 9.99830723e-01, 1.10256100e-04,
        1.99196063e-12, 1.01096375e-05, 1.21922128e-07, 2.48547764e-13,
        1.40628060e-06, 2.96733926e-12],
       [4.02854255e-07, 9.98521388e-01, 1.10012195e-04, 1.41655546e-05,
        6.74644907e-05, 2.06963214e-05, 8.29567871e-05, 8.31262674e-04,
        3.51338735e-04, 4.56514584e-07],
       [9.99652505e-01, 9.61754623e-08, 1.17975469e-04, 2.82903585e-07,
        3.42341900e-06, 2.52182999e-05, 1.14869945e-04, 3.15096804e-05,
        7.42172119e-08, 5.40129477e-05],
       [2.50407902e-06, 1.40345041e-10, 6.87319471e-07, 5.39026024e-09,
        9.97210801e-01, 2.12295930e-07, 2.00111708e-06, 4.19272374e-06,
        1.51631718e-06, 2.77800485e-03]], dtype=float32)>

### Ensure you have the latest TensorFlow gpu release installed

In [24]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

Num GPUs Available:  1


In [29]:
# Place tensors on the CPU
with tf.device('/CPU:0'):
  a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])

c = tf.matmul(a, b)
print(c)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [30]:
# Place tensors on the GPU
with tf.device('/GPU:0'):
  a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])

c = tf.matmul(a, b)
print(c)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)
